
/*
 *  Project:            Pipelined-Packet-Parser.
 *  Module name:        Testbench.
 *  Description:        Testbench of Pipelined-Packet-Parser.
 *  Last updated date:  2024.06.07.
 *
 *  Copyright (C) 2021-2024 Junnan Li <lijunnan@nudt.edu.cn>.
 *  Copyright and related rights are licensed under the MIT license.
 *
 */


`timescale 1ns/1ps
import parser_pkg::*;

// `define AUTO_CONF

module Testbench_wrapper(
);

`ifdef DUMP_FSDB
  initial begin
    $fsdbDumpfile("wave.fsdb");
    $fsdbDumpvars(0,"+all");
    $fsdbDumpMDA();
    $vcdpluson;
    $vcdplusmemon;
  end
`endif
  
  reg clk,rst_n;
  initial begin
    clk = 0;
    rst_n = 1;
    #2  rst_n = 0;
    #10 rst_n = 1;
    forever #1 clk = ~clk;
  end
  initial begin  
      #2000 $finish;
  end

  reg           r_rule_wren;
  reg   [31:0]  r_rule_addr;
  reg   [31:0]  r_rule_wdata;
  reg   [133:0] r_pkt;
  reg           r_pkt_valid;
  wire                              w_phv_valid;
  wire  [HEAD_WIDTH+TAG_WIDTH-1:0]  w_phv;

  //* recv pkt, and gen phv;
  Gen_PHV_and_Conf_Parser gen_PHV_and_conf_parer(
    .i_clk                (clk          ),
    .i_rst_n              (rst_n        ),
    .i_pkt_valid          (r_pkt_valid    ),
    .i_pkt                (r_pkt          ),
    .i_inport             (8'b0           ),
    .o_pkt_valid          (   ),
    .o_pkt                (  ),
    .o_phv_valid          (w_phv_valid ),
    .o_phv                (w_phv       ),
    .o_meta               (      ),

    .o_rule_valid         (    ),
    .o_layerID            (    ),
    .o_ruleID             (   ),
    .o_type_rule          (    )
  );

  Gen_128b_Pkt Gen_128b_Pkt(
    .i_clk      (clk),
    .i_rst_n    (rst_n),
    .o_pkt      (),
    .o_pkt_valid(),
    .i_phv_valid(w_phv_valid),
    .i_phv      (w_phv)
  );

  localparam NORMAL_PKT1      = {128'h000a_3500_0102_00e0_4d6d_a7b3_0800_4500,
                                  128'h0028_e84b_4000_4006_ce61_c0a8_010a_c0a8,
                                  128'h01c8_1389_c001_3876_6005_0000_1986_5010,
                                  128'hfad8_843d_0000_3876_6005_0000_1986_5010,
                                  128'h1,128'h2,128'h3,128'h4};
//* generated by python script

  initial begin
    r_pkt_valid = 1'b0;
    #100 begin
      r_pkt_valid = 1'b1;
      r_pkt = {2'b01,4'hf,NORMAL_PKT1[128*3+:128]};
    end
    #2 r_pkt = {2'b00,4'hf,NORMAL_PKT1[128*2+:128]};
    #2 r_pkt = {2'b00,4'hf,NORMAL_PKT1[128*1+:128]};
    #2 r_pkt = {2'b10,4'hf,NORMAL_PKT1[128*0+:128]};
    #2 r_pkt_valid = 1'b0;
    #100 begin
      r_pkt_valid = 1'b1;
      r_pkt = {2'b01,4'hf,NORMAL_PKT1[128*7+:128]};
    end
    #2 r_pkt = {2'b00,4'hf,NORMAL_PKT1[128*6+:128]};
    #2 r_pkt = {2'b00,4'hf,NORMAL_PKT1[128*5+:128]};
    #2 r_pkt = {2'b00,4'hf,NORMAL_PKT1[128*4+:128]};
    #2 r_pkt = {2'b00,4'hf,NORMAL_PKT1[128*3+:128]};
    #2 r_pkt = {2'b00,4'hf,NORMAL_PKT1[128*2+:128]};
    #2 r_pkt = {2'b10,4'hf,NORMAL_PKT1[128*1+:128]};
    #2 r_pkt_valid = 1'b0;
  end

endmodule
